expressions_to_track = [
    'second amendment', 
    'gun control', 
    'guns in america', 
    '2nd amendment', 
    'guns control', 
    'america guns',
    'america shooting', 
    'shooting america', 
    'control guns', 
    'guns america', 
    'usa guns', 
    'guns usa', 
    'usa shooting', 
    'guns in usa',
    'amendment second',
    'amendment 2nd',
    '2 amendment',
    'amendment 2', 
    'control guns',
    'shooring usa',
    'shooring america',
    'america shooting'
]
